### ISSUE TITLE
Error: unknown command "internal" for "slurp"

### ISSUE THREAD

**Issue by testacc0808** [appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training#19] opened 2020-06-06 16:39 UTC
![image](https://user-images.githubusercontent.com/64963907/83949550-166bb500-a857-11ea-8dc7-bc53c0834d3c.png)

Does the installed slurp on cloudhacker really support the "internal" command?

*I have configured my aws profile under ~/.aws/credentials

**Comment by 0xbharath** [comment] 2020-06-23 03:20
Good catch. The Slurp part was intended to be a demo. Slurp binary installed on cloudhacker is  v1.

Slurp v2 supports `internal` command and this is the version under active development. I have added the steps to download and run Slurp v2 with `internal` mode. 

https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training/pull/22

**Comment by riyazwalikar** [comment] 2020-06-27 13:35
Closing this as the documentation is now updated.

**Closed as completed by riyazwalikar** 2020-06-27 13:35 UTC
